/**
 * One-time admin migration: set ProtocolConfig.validator_pubkey on devnet.
 * Triggers the realloc 77 -> 109 bytes via the Anchor realloc constraint.
 *
 * Master-list #146 Phase 3.
 *
 * Run from protocol-core directory:
 *   npx tsx scripts/set-validator-pubkey.ts
 *
 * The validator pubkey is read from the local validator-signing keypair
 * file at /IAM/.config/validator-signing-devnet.json (gitignored). That
 * key was generated 2026-04-28 and is the same pubkey the validator
 * service uses to sign mint receipts.
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Connection, Keypair } from "@solana/web3.js";
import fs from "fs";
import path from "path";

const REGISTRY_PROGRAM_ID = new PublicKey(
  "6VBs3zr9KrfFPGd6j7aGBPQWwZa5tajVfA7HN6MMV9VW"
);

async function main() {
  const adminPath =
    process.env.ADMIN_KEYPAIR_PATH ||
    path.resolve(__dirname, "../../.config/admin-devnet.json");
  const validatorPath =
    process.env.VALIDATOR_SIGNING_KEYPAIR_PATH ||
    path.resolve(__dirname, "../../.config/validator-signing-devnet.json");

  const adminRaw = fs.readFileSync(adminPath, "utf-8");
  const admin = Keypair.fromSecretKey(new Uint8Array(JSON.parse(adminRaw)));

  const validatorRaw = fs.readFileSync(validatorPath, "utf-8");
  const validatorPubkey = Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(validatorRaw))
  ).publicKey;

  console.log(`Admin:                  ${admin.publicKey.toBase58()}`);
  console.log(`Validator pubkey:       ${validatorPubkey.toBase58()}`);
  console.log(`Registry program:       ${REGISTRY_PROGRAM_ID.toBase58()}`);

  const connection = new Connection(
    "https://api.devnet.solana.com",
    "confirmed"
  );
  const wallet = new anchor.Wallet(admin);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });

  // Read local IDL from target/idl rather than fetching the on-chain
  // IDL — `solana program deploy` only replaces bytecode, it doesn't
  // sync the on-chain IDL upload, so a fresh setValidatorPubkey method
  // wouldn't appear in fetchIdl until `anchor idl upgrade` runs. The
  // local IDL is regenerated by `anchor build` and matches the freshly
  // deployed bytecode exactly.
  const idlPath = path.resolve(__dirname, "../target/idl/entros_registry.json");
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf-8"));
  const program = new anchor.Program(idl, provider) as any;

  const [protocolConfigPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("protocol_config")],
    REGISTRY_PROGRAM_ID
  );
  console.log(`ProtocolConfig PDA:     ${protocolConfigPda.toBase58()}`);

  const before = await connection.getAccountInfo(protocolConfigPda);
  if (!before) {
    throw new Error("ProtocolConfig PDA not found — initialize registry first");
  }
  console.log(`Account size before:    ${before.data.length} bytes`);

  const sig = await program.methods
    .setValidatorPubkey(validatorPubkey)
    .accountsPartial({
      admin: admin.publicKey,
      protocolConfig: protocolConfigPda,
    })
    .rpc();

  console.log(`tx signature:           ${sig}`);

  const after = await connection.getAccountInfo(protocolConfigPda);
  if (!after) throw new Error("ProtocolConfig disappeared after tx (impossible)");
  console.log(`Account size after:     ${after.data.length} bytes`);

  if (after.data.length !== 109) {
    console.warn(
      `WARNING: expected 109 bytes after migration; got ${after.data.length}`
    );
  } else {
    console.log("✅ Account resized 77 -> 109 bytes");
  }

  // Read the validator_pubkey field at offset 77 (32 bytes).
  const written = new PublicKey(after.data.slice(77, 109));
  console.log(`Validator pubkey on-chain: ${written.toBase58()}`);
  if (!written.equals(validatorPubkey)) {
    throw new Error("Validator pubkey on-chain does not match expected");
  }
  console.log("✅ Validator pubkey written correctly");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
